In [73]:
import numpy as np
import pandas as pd

Generating random dataset

In [74]:
X=np.vstack([(np.random.rand(10,2)*5),(np.random.rand(10,2)*10)])
print(X)
y=np.random.randint(0,2,20)
y=y.reshape(20,1)
print(y)


[[4.34425465 2.80675228]
 [4.2851287  4.26737488]
 [3.19025196 1.36400652]
 [0.07662999 4.77266825]
 [1.77132387 3.25834262]
 [4.29498808 0.52841056]
 [1.62853178 1.5922779 ]
 [2.41972014 2.70589021]
 [4.67861826 2.52336408]
 [4.16750825 1.47068213]
 [6.44768342 6.42856136]
 [4.07072098 7.05627918]
 [0.77012842 6.79071217]
 [1.14956252 0.45372655]
 [2.70376211 8.36134064]
 [1.74335643 5.00026734]
 [7.77758481 4.02236024]
 [0.11833114 2.18243356]
 [6.65690018 8.38745362]
 [2.98395861 8.3586099 ]]
[[0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]]


Random dataset


In [75]:
dataset=pd.DataFrame(X,columns=["x1" , "x2"])
dataset["y"]=y

In [76]:
y=np.random.randint(0,2,20)
y=y.reshape(20,1)
y

array([[1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1]])

Dataset

In [77]:
dataset

x1        x2  y
0   4.344255  2.806752  0
1   4.285129  4.267375  1
2   3.190252  1.364007  0
3   0.076630  4.772668  1
4   1.771324  3.258343  1
5   4.294988  0.528411  0
6   1.628532  1.592278  1
7   2.419720  2.705890  0
8   4.678618  2.523364  0
9   4.167508  1.470682  0
10  6.447683  6.428561  0
11  4.070721  7.056279  0
12  0.770128  6.790712  0
13  1.149563  0.453727  0
14  2.703762  8.361341  0
15  1.743356  5.000267  1
16  7.777585  4.022360  0
17  0.118331  2.182434  0
18  6.656900  8.387454  1
19  2.983959  8.358610  1

one hot encoding

In [78]:
Z=np.zeros((20,2))
for i in range(20):
  Z[i,y[i]]=1

In [79]:
X.shape

(20, 2)

initiating weight and bias

In [80]:
wi_1=np.random.randn(2,2)
bi_1=np.random.randn(2)
wi_2=np.random.randn(2,2)
bi_2=np.random.randn(2)

In [81]:
wi_1

array([[ 0.52167706, -0.91360408],
       [ 1.75495262,  0.83007299]])

In [82]:
bi_1

array([-0.36869033,  0.22380611])

In [83]:
wi_2

array([[ 1.16555491, -1.15102825],
       [-0.13370417,  0.4176708 ]])

In [84]:
bi_2

array([-1.06280567,  3.14999781])

In [85]:
X

array([[4.34425465, 2.80675228],
       [4.2851287 , 4.26737488],
       [3.19025196, 1.36400652],
       [0.07662999, 4.77266825],
       [1.77132387, 3.25834262],
       [4.29498808, 0.52841056],
       [1.62853178, 1.5922779 ],
       [2.41972014, 2.70589021],
       [4.67861826, 2.52336408],
       [4.16750825, 1.47068213],
       [6.44768342, 6.42856136],
       [4.07072098, 7.05627918],
       [0.77012842, 6.79071217],
       [1.14956252, 0.45372655],
       [2.70376211, 8.36134064],
       [1.74335643, 5.00026734],
       [7.77758481, 4.02236024],
       [0.11833114, 2.18243356],
       [6.65690018, 8.38745362],
       [2.98395861, 8.3586099 ]])

In [86]:
X.dot(wi_1.T)

array([[-0.29796235,  9.95377033],
       [-1.66323777, 11.06243045],
       [ 0.41811933,  6.730966  ],
       [-4.32035308,  4.096145  ],
       [-2.05277608,  5.81325167],
       [ 1.7578387 ,  7.97611992],
       [-0.60514392,  4.179703  ],
       [-1.20979985,  6.49258056],
       [ 0.13537208, 10.30532973],
       [ 0.83047224,  8.53455304],
       [-2.50955138, 16.65155405],
       [-4.32304371, 13.00114919],
       [-5.80226402,  6.98832563],
       [ 0.18517396,  2.39405392],
       [-6.22846426, 11.68549742],
       [-3.65879559,  7.21009479],
       [ 0.38254283, 16.98814543],
       [-1.93214957,  2.0192447 ],
       [-4.19005975, 18.6447431 ],
       [-6.07979737, 12.17496228]])

forward propogation

In [87]:
def forward_prop(X,wi_1,bi_1,wi_2,bi_2):
  #first 
  M =1/(1+np.exp(-(X.dot(wi_1.T)+bi_1)))
  #second
  A=M.dot(wi_2)+bi_2
  expA=np.exp(A)
  Y=expA/expA.sum(axis=1,keepdims=True)
  return Y,M

In [88]:
forward_prop(X,wi_1,bi_1,wi_2,bi_2)

(array([[0.01837417, 0.98162583],
        [0.01103377, 0.98896623],
        [0.02720585, 0.97279415],
        [0.0086988 , 0.9913012 ],
        [0.01021181, 0.98978819],
        [0.05167596, 0.94832404],
        [0.01594558, 0.98405442],
        [0.01252587, 0.98747413],
        [0.02319415, 0.97680585],
        [0.03412466, 0.96587534],
        [0.00955732, 0.99044268],
        [0.00863614, 0.99136386],
        [0.00850177, 0.99149823],
        [0.02473765, 0.97526235],
        [0.00848429, 0.99151571],
        [0.00880758, 0.99119242],
        [0.02665234, 0.97334766],
        [0.01098324, 0.98901676],
        [0.00866154, 0.99133846],
        [0.00848853, 0.99151147]]), array([[0.33924677, 0.99996199],
        [0.11589122, 0.99998746],
        [0.51235473, 0.99904684],
        [0.00911169, 0.98687405],
        [0.08155035, 0.99761712],
        [0.80045625, 0.9997254 ],
        [0.27411692, 0.98791354],
        [0.17100942, 0.99879056],
        [0.44193362, 0.99997325],
        [0.61

Backward propogation


In [89]:
#hidden layer transpose 
#actual - predicted
def diff_wi_2(H,Z,Y):
  return H.T.dot(Z-Y)

In [90]:
#diff wrt to outer later weights
def diff_wi_1(X,H,Z,output,wi_2):
  dz=(Z-output).dot(wi_2.T)*H*(1-H)
  return H.T.dot(dz)

In [97]:

def diff_b2(Z,Y):
  return (Z-Y).sum(axis=0)

def diff_b1(Z,Y,wi_2,H):
  return ((Z-Y).dot(wi_2.T) * H * (1-H)).sum(axis=0)

In [93]:
learning_rate = 0.1
for epoch in range(4000):
  output,hidden=forward_prop(X,wi_1,bi_1,wi_2,bi_2)
  wi_2 += learning_rate * diff_wi_2(hidden,Z,output)
  bi_2 += learning_rate * diff_b2(Z,output)
  wi_1 += learning_rate * diff_wi_1(X,hidden,Z,output,wi_2).T
  bi_1 += learning_rate * diff_b1(Z,output,wi_2,hidden)

new predicting data point


In [92]:
X_test=np.array([3,2])
hidden_output = 1 / (1+np.exp(-X_test.dot(wi_1.T) + bi_1))
outer= hidden_output.dot(wi_2) + bi_2
expA = np.exp(outer)
Y = expA / expA.sum()
print("prob class 0>>>> {} \n prob of class 1>>>> ({}) ".format(Y[0],Y[1]))

prob class 0>>>> 0.0280973242284164 
 prob of class 1>>>> (0.9719026757715836) 
